name: aws
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - awscli=2.16.7
  - awscrt=0.20.10
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cffi=1.16.0
  - colorama=0.4.6
  - cryptography=40.0.2
  - distro=1.8.0
  - docutils=0.19
  - jmespath=1.0.1
  - jq=1.6
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - make=4.3
  - ncurses=6.5
  - oniguruma=6.9.7.1
  - openssl=3.3.1
  - pip=24.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - pycparser=2.22
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.8.2
  - python_abi=3.11
  - readline=8.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - s2n=1.4.16
  - setuptools=70.0.0
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2024a
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
